services:
  - type: web
    name: elites-fight
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build && (npx drizzle-kit push || true)
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: MERCADO_PAGO_ACCESS_TOKEN
        value: APP_USR-3099883387466407-071810-702728ea8137984ae015dac8a2223668-472145272
      - key: ADMIN_PASSWORD
        value: A2m8o9j3
