import { pgTable, serial, text, timestamp, varchar, boolean, jsonb, pgEnum, integer } from "drizzle-orm/pg-core";

export const roleEnum = pgEnum("role", ["user", "admin"]);
export const planEnum = pgEnum("plan", ["free", "pro", "elite"]);
export const planCodeEnum = pgEnum("plan_code", ["free", "pro", "elite"]);

/**
 * Core user table backing auth flow.
 */
export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: roleEnum("role").default("user").notNull(),
  plan: planEnum("plan").default("free").notNull(),
  suspended: boolean("suspended").default(false).notNull(),
  sheetsGenerated: integer("sheetsGenerated").default(0).notNull(),
  aiUsesLeft: integer("aiUsesLeft").default(0).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

/**
 * Categories group templates.
 */
export const categories = pgTable("categories", {
  id: serial("id").primaryKey(),
  name: varchar("name", { length: 120 }).notNull(),
  slug: varchar("slug", { length: 140 }).notNull().unique(),
  description: text("description"),
  icon: varchar("icon", { length: 60 }),
  displayOrder: integer("displayOrder").default(0).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().notNull(),
});

/**
 * Spreadsheet templates available for generation.
 */
export const templates = pgTable("templates", {
  id: serial("id").primaryKey(),
  categoryId: integer("categoryId").notNull(),
  name: varchar("name", { length: 200 }).notNull(),
  slug: varchar("slug", { length: 220 }).notNull().unique(),
  description: text("description"),
  plan: planEnum("plan").default("free").notNull(),
  columns: jsonb("columns").notNull(),
  sampleRows: jsonb("sampleRows"),
  headerColor: varchar("headerColor", { length: 20 }).default("#D4AF37"),
  accentColor: varchar("accentColor", { length: 20 }).default("#1A1A1A"),
  isFeatured: boolean("isFeatured").default(false).notNull(),
  isActive: boolean("isActive").default(true).notNull(),
  displayOrder: integer("displayOrder").default(0).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().notNull(),
});

/**
 * Record of each spreadsheet generated by a user.
 */
export const generatedSheets = pgTable("generatedSheets", {
  id: serial("id").primaryKey(),
  userId: integer("userId").notNull(),
  templateId: integer("templateId").notNull(),
  templateName: varchar("templateName", { length: 200 }).notNull(),
  customName: varchar("customName", { length: 200 }).notNull(),
  fileUrl: text("fileUrl"),
  fileKey: varchar("fileKey", { length: 255 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

/**
 * Plan definitions with limits and pricing.
 */
export const plans = pgTable("plans", {
  id: serial("id").primaryKey(),
  code: planCodeEnum("code").notNull().unique(),
  name: varchar("name", { length: 60 }).notNull(),
  priceMonthly: varchar("priceMonthly", { length: 20 }).default("0"),
  priceYearly: varchar("priceYearly", { length: 20 }).default("0"),
  description: text("description"),
  features: jsonb("features").notNull(),
  maxTemplates: integer("maxTemplates").default(5).notNull(),
  maxThemes: integer("maxThemes").default(5).notNull(),
  maxAiUses: integer("maxAiUses").default(0).notNull(),
  unlimitedSheets: boolean("unlimitedSheets").default(false).notNull(),
  hasWatermark: boolean("hasWatermark").default(true).notNull(),
  customLogo: boolean("customLogo").default(false).notNull(),
  isActive: boolean("isActive").default(true).notNull(),
  displayOrder: integer("displayOrder").default(0).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().notNull(),
});

/**
 * Site-wide configurable content.
 */
export const siteSettings = pgTable("siteSettings", {
  id: serial("id").primaryKey(),
  key: varchar("key", { length: 80 }).notNull().unique(),
  value: jsonb("value").notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().notNull(),
});

/**
 * Promotional coupons.
 */
export const coupons = pgTable("coupons", {
  id: serial("id").primaryKey(),
  code: varchar("code", { length: 40 }).notNull().unique(),
  discountPercent: integer("discountPercent").default(0).notNull(),
  maxUses: integer("maxUses").default(0).notNull(),
  usesCount: integer("usesCount").default(0).notNull(),
  expiresAt: timestamp("expiresAt"),
  isActive: boolean("isActive").default(true).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().notNull(),
});

/**
 * Broadcast announcements sent to users.
 */
export const announcements = pgTable("announcements", {
  id: serial("id").primaryKey(),
  title: varchar("title", { length: 200 }).notNull(),
  message: text("message").notNull(),
  createdBy: integer("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
