import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, boolean, json } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extended with plan info for ELITES_FIGHT.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  plan: mysqlEnum("plan", ["free", "pro", "elite"]).default("free").notNull(),
  suspended: boolean("suspended").default(false).notNull(),
  sheetsGenerated: int("sheetsGenerated").default(0).notNull(),
  aiUsesLeft: int("aiUsesLeft").default(0).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Categories group templates (e.g. Finance, Tournaments, Reports).
 */
export const categories = mysqlTable("categories", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 120 }).notNull(),
  slug: varchar("slug", { length: 140 }).notNull().unique(),
  description: text("description"),
  icon: varchar("icon", { length: 60 }),
  displayOrder: int("displayOrder").default(0).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Category = typeof categories.$inferSelect;
export type InsertCategory = typeof categories.$inferInsert;

/**
 * Spreadsheet templates available for generation.
 * `columns` stores a JSON array describing each column (name, type, width, formula, etc.).
 * `sampleRows` stores optional sample data rows.
 */
export const templates = mysqlTable("templates", {
  id: int("id").autoincrement().primaryKey(),
  categoryId: int("categoryId").notNull(),
  name: varchar("name", { length: 200 }).notNull(),
  slug: varchar("slug", { length: 220 }).notNull().unique(),
  description: text("description"),
  plan: mysqlEnum("plan", ["free", "pro", "elite"]).default("free").notNull(),
  columns: json("columns").notNull(),
  sampleRows: json("sampleRows"),
  headerColor: varchar("headerColor", { length: 20 }).default("#D4AF37"),
  accentColor: varchar("accentColor", { length: 20 }).default("#1A1A1A"),
  isFeatured: boolean("isFeatured").default(false).notNull(),
  isActive: boolean("isActive").default(true).notNull(),
  displayOrder: int("displayOrder").default(0).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Template = typeof templates.$inferSelect;
export type InsertTemplate = typeof templates.$inferInsert;

/**
 * Record of each spreadsheet generated by a user.
 */
export const generatedSheets = mysqlTable("generatedSheets", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  templateId: int("templateId").notNull(),
  templateName: varchar("templateName", { length: 200 }).notNull(),
  customName: varchar("customName", { length: 200 }).notNull(),
  fileUrl: text("fileUrl"),
  fileKey: varchar("fileKey", { length: 255 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type GeneratedSheet = typeof generatedSheets.$inferSelect;
export type InsertGeneratedSheet = typeof generatedSheets.$inferInsert;

/**
 * Plan definitions with limits and pricing.
 */
export const plans = mysqlTable("plans", {
  id: int("id").autoincrement().primaryKey(),
  code: mysqlEnum("code", ["free", "pro", "elite"]).notNull().unique(),
  name: varchar("name", { length: 60 }).notNull(),
  priceMonthly: varchar("priceMonthly", { length: 20 }).default("0"),
  priceYearly: varchar("priceYearly", { length: 20 }).default("0"),
  description: text("description"),
  features: json("features").notNull(),
  maxTemplates: int("maxTemplates").default(5).notNull(),
  maxThemes: int("maxThemes").default(5).notNull(),
  maxAiUses: int("maxAiUses").default(0).notNull(),
  unlimitedSheets: boolean("unlimitedSheets").default(false).notNull(),
  hasWatermark: boolean("hasWatermark").default(true).notNull(),
  customLogo: boolean("customLogo").default(false).notNull(),
  isActive: boolean("isActive").default(true).notNull(),
  displayOrder: int("displayOrder").default(0).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Plan = typeof plans.$inferSelect;
export type InsertPlan = typeof plans.$inferInsert;

/**
 * Site-wide configurable content (home texts, FAQ, footer, banners).
 */
export const siteSettings = mysqlTable("siteSettings", {
  id: int("id").autoincrement().primaryKey(),
  key: varchar("key", { length: 80 }).notNull().unique(),
  value: json("value").notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type SiteSetting = typeof siteSettings.$inferSelect;
export type InsertSiteSetting = typeof siteSettings.$inferInsert;

/**
 * Promotional coupons.
 */
export const coupons = mysqlTable("coupons", {
  id: int("id").autoincrement().primaryKey(),
  code: varchar("code", { length: 40 }).notNull().unique(),
  discountPercent: int("discountPercent").default(0).notNull(),
  maxUses: int("maxUses").default(0).notNull(),
  usesCount: int("usesCount").default(0).notNull(),
  expiresAt: timestamp("expiresAt"),
  isActive: boolean("isActive").default(true).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Coupon = typeof coupons.$inferSelect;
export type InsertCoupon = typeof coupons.$inferInsert;

/**
 * Broadcast announcements sent to users.
 */
export const announcements = mysqlTable("announcements", {
  id: int("id").autoincrement().primaryKey(),
  title: varchar("title", { length: 200 }).notNull(),
  message: text("message").notNull(),
  createdBy: int("createdBy"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Announcement = typeof announcements.$inferSelect;
export type InsertAnnouncement = typeof announcements.$inferInsert;
